spring:
  application:
    name: Document_Workflow

  datasource:
    url: jdbc:mariadb://localhost:3306/document_workflow?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  # Redis configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 2000ms

  # Spring Security
  security:
    oauth2:
      resourceserver: {}

server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG

minio:
  url: http://103.118.29.245:9000
  access-key: hFrD4YJb75YxUQDPKXfQ
  secret-key: zPZ3J59xClieEJdKLVgBotjHnpwHM8HmD8DGIu41
  bucket: your-bucket-name