spring:
  application:
    name: Document_Workflow

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:mariadb://localhost:3306/document_workflow?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  # kafka
  kafka:
    bootstrap-servers: 103.118.29.245:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: document-comment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  # redis
  data:
    redis:
      host: 103.118.29.245
      port: 6379
      timeout: 2000

  mail:
    host: smtp.gmail.com
    port: 587
    username: hantho1107@gmail.com
    password: pidz dbgi tkcr caep
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # security
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://103.118.29.245:8443/realms/document-api

server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.kafka: INFO

minio:
  url: http://103.118.29.245:9000
  access-key: hFrD4YJb75YxUQDPKXfQ
  secret-key: zPZ3J59xClieEJdKLVgBotjHnpwHM8HmD8DGIu41
  bucket: dung
